// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_ZpbRMfUsXyJeIUjWGbZjVwnB62s4rE',
    appId: '1:31784643804:web:66101f5d7287ba6d4c9819',
    messagingSenderId: '31784643804',
    projectId: 'projetoddm1semestre',
    authDomain: 'projetoddm1semestre.firebaseapp.com',
    storageBucket: 'projetoddm1semestre.firebasestorage.app',
    measurementId: 'G-71YRRHK2VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlAovjqAI8JTLAfegP3KYDxj-UUCmcrE',
    appId: '1:31784643804:android:0c927c6cfb8acf2b4c9819',
    messagingSenderId: '31784643804',
    projectId: 'projetoddm1semestre',
    storageBucket: 'projetoddm1semestre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3dmwajsUbBo91q0m3X_az7sV8VYkRlA0',
    appId: '1:31784643804:ios:fa9c197b453c90664c9819',
    messagingSenderId: '31784643804',
    projectId: 'projetoddm1semestre',
    storageBucket: 'projetoddm1semestre.firebasestorage.app',
    iosBundleId: 'alvassete.com.br.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3dmwajsUbBo91q0m3X_az7sV8VYkRlA0',
    appId: '1:31784643804:ios:fa9c197b453c90664c9819',
    messagingSenderId: '31784643804',
    projectId: 'projetoddm1semestre',
    storageBucket: 'projetoddm1semestre.firebasestorage.app',
    iosBundleId: 'alvassete.com.br.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv_ZpbRMfUsXyJeIUjWGbZjVwnB62s4rE',
    appId: '1:31784643804:web:c9e081f83279ec2a4c9819',
    messagingSenderId: '31784643804',
    projectId: 'projetoddm1semestre',
    authDomain: 'projetoddm1semestre.firebaseapp.com',
    storageBucket: 'projetoddm1semestre.firebasestorage.app',
    measurementId: 'G-Q5CXC32VRX',
  );
}
